---
- name: Installation base
  hosts: all
  tasks:

    - name: Create config terminator directory
      file:
        path: "/home/{{ user_name }}/.config/terminator"
        state: directory
        owner: "{{ user_name }}"

    - name: Configure terminator
      copy:
        src: ../files/terminator.config
        dest: "/home/{{ user_name }}/.config/terminator/config"
        owner: "{{ user_name }}"

    - name: Configure kde plasma
      copy:
        src: "../files/{{ item }}.config"
        dest: "/home/{{ user_name }}/.config/{{ item }}"
        owner: "{{ user_name }}"
      loop:
        - kglobalshortcutsrc
        - kwinrc
        - powermanagementprofilesrc

    - name: ksmserverrc
      community.general.ini_file:
        path: "/home/{{ user_name }}/.config/ksmserverrc"
        section: General
        option: loginMode
        value: emptySession
        backup: yes

    - name: kxkbrc LayoutList
      community.general.ini_file:
        path: "/home/{{ user_name }}/.config/kxkbrc"
        section: Layout
        option: LayoutList
        value: es,us
        backup: yes

    - name: kxkbrc Options
      community.general.ini_file:
        path: "/home/{{ user_name }}/.config/kxkbrc"
        section: Layout
        option: Options
        value: caps:ctrl_modifier
        backup: yes

    - name: Configure git
      copy:
        src: ../files/git.config
        dest: "/home/{{ user_name }}/.gitconfig"
        owner: "{{ user_name }}"

    - name: Create config ssh directory
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"

    - name: Configure ssh
      copy:
        src: "../files/{{ item }}"
        dest: "/home/{{ user_name }}/.ssh/{{ item }}"
        owner: "{{ user_name }}"
        mode: 0600
      loop:
        - id_rsa
        - id_rsa.pub

    - name: Configure bashrc
      copy:
        src: ../files/bashrc
        dest: "/home/{{ user_name }}/.bashrc"
        owner: "{{ user_name }}"
