---
- name: Installation base
  hosts: all
  tasks:

    - name: Download firefox
      get_url:
        url: "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=linux64&lang=es-ES"
        dest: /opt/firefox.tar.bz2
        owner: cesar

    - name: Install firefox
      unarchive:
        src: /opt/firefox.tar.bz2
        dest: /opt/
        remote_src: yes
        owner: cesar
        group: users

    - name: Create firefox bin link
      file:
        src: /opt/firefox/firefox
        dest: /usr/bin/firefox
        state: link
