---
- name: Installation base
  hosts: all
  vars:
    ansible_ssh_user: root
  tasks:

    - name: Create user
      user:
        name: "{{ user_name }}"
        uid: 1000
        group: users
        groups: power,storage,wheel
        append: yes
        password: "{{ user_password_hash }}"

    - name: Add user to sudoers
      community.general.sudoers:
        name: allow-wheel-group
        group: wheel
        state: present
        nopassword: false
        commands: ALL

    - name: Install pacman-contrib
      pacman:
        name: pacman-contrib

    - name: Create mirrorlist backup
      copy:
        src: /etc/pacman.d/mirrorlist
        dest: /etc/pacman.d/mirrorlist.backup
        remote_src: yes
      when: false # TODO idempotence

    - name: Rank mirrorlist
      command: "rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist"
      when: false # TODO idempotence

    - name: Install X
      pacman:
        name:
          - mesa
          - plasma

    - name: Enable X
      service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - sddm
        - NetworkManager

    - name: Install necessary packages
      pacman:
        name:
          - htop
          - bind-tools
          - usbutils

    - name: Set timezone to Europa/España
      community.general.timezone:
        name: Europe/Madrid

    - name: Install chrony
      package:
        name: chrony

    - name: Configure chrony
      ansible.builtin.copy:
        dest: /etc/chrony.conf
        content: |
          pool pool.ntp.org iburst maxsources 4 offline
          server time.cloudflare.com iburst nts
          makestep 1.0 3
          rtcsync

    - name: Start and enable chrony
      service:
        name: chronyd
        state: started
        enabled: true