# Note: This playbook needs a especific ansible colletion: kewlfft.aur
# ansible-galaxy collection install kewlfft.aur
# https://github.com/kewlfft/ansible-aur
---
- name: Installation base
  hosts: all
  tasks:

    - name: Install yay dependencies
      pacman:
        name:
          - git
          - base-devel
      become: yes
      become_method: sudo
      tags:
        - installation

    - name: Clone yay repository
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: /home/{{ ansible_ssh_user }}/tmp/yay
      tags:
        - installation

    - name: Wheel group no password on sudo
      community.general.sudoers:
        name: allow-wheel-group
        group: wheel
        state: present
        nopassword: true
        commands: ALL
      become: yes
      become_method: sudo
      tags:
        - always

    - name: Make yay package
      command: makepkg -si --needed --noconfirm
      args:
        chdir: /home/{{ ansible_ssh_user }}/tmp/yay
      tags:
        - installation

    - name: Install packages from AUR
      kewlfft.aur.aur:
        use: yay
        name:
          - visual-studio-code-bin
          - sddm-git
      tags:
        - packages

    - name: Reset wheel group password on sudo
      community.general.sudoers:
        name: allow-wheel-group
        group: wheel
        state: present
        nopassword: false
        commands: ALL
      become: yes
      become_method: sudo
      tags:
        - always
